version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      # El '|| true' evita que CodeBuild se detenga si Cypress detecta algún test fallido
      - npm run cy:parallel || true
  post_build:
    commands: 
      - npm run generar-reporte || true
      # Sincroniza la carpeta del reporte con S3 (S3 asigna los Content-Type de forma automática)
      - aws s3 sync allure-report/ s3://contenedor-reporte-de-pruebas/ --delete