version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      # El '|| true' evita que CodeBuild se detenga si Cypress detecta algún test fallido
      - npm run cy:parallel || true
  post_build:
    commands: 
      # Genera el reporte de Allure antes de subirlo
      - npm run generar-reporte || true
      # Sincroniza y aplica los permisos sobre tu bucket
      - aws s3 sync allure-report s3://contenedor-reporte-de-pruebas/
      - aws s3 cp --recursive --acl public-read s3://contenedor-reporte-de-pruebas/ s3://contenedor-reporte-de-pruebas/ --metadata-directive REPLACE